version = "3.11.5"
runner.dialect = scala213
fileOverride {
  "glob:**/build.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/.bsp/out/mill-build/generatedScriptSources.dest/support/**" {
     runner.dialect = scala3
  }
}
